# -*- coding: utf-8 -*-
"""Copy of Text_Generation_RNN_LSTM_GRU_Learning_Project_jaivardhan_week_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-QfMIvppImHSU376W38XIg5H5PZU1hy
"""

"""
Text Generation: Vanilla RNN vs LSTM vs GRU
PEP8 compliant | Modular | Production-grade
"""

import os
import warnings
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
warnings.filterwarnings("ignore")

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, GRU, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

print(f"TensorFlow: {tf.__version__}")

CORPUS = """
deep learning is transforming artificial intelligence
recurrent neural networks are useful for sequential data
lstm helps remember long term dependencies
gru is faster and simpler than lstm
text generation models predict the next word
deep learning models can generate meaningful sentences
neural networks learn patterns from text data
artificial intelligence is the future of technology
sequence models capture temporal patterns in language
deep neural networks have many hidden layers
"""


def build_sequences(corpus: str):
    """Tokenize corpus and build n-gram training sequences."""
    tokenizer = Tokenizer()
    tokenizer.fit_on_texts([corpus])
    total_words = len(tokenizer.word_index) + 1

    input_sequences = []
    for line in corpus.strip().split("\n"):
        token_list = tokenizer.texts_to_sequences([line])[0]
        for i in range(1, len(token_list)):
            input_sequences.append(token_list[: i + 1])

    max_len = max(len(s) for s in input_sequences)
    padded = pad_sequences(input_sequences, maxlen=max_len, padding="pre")

    X = padded[:, :-1]
    y = padded[:, -1]

    return tokenizer, total_words, max_len, X, y


tokenizer, total_words, max_len, X, y = build_sequences(CORPUS)
print(f"[CP1] Vocab: {total_words} | Max seq len: {max_len} | X: {X.shape} | y: {y.shape}")


def build_model(arch: str, total_words: int, max_len: int, units: int = 128) -> Sequential:
    """
    Factory: returns compiled model for 'rnn', 'lstm', 'gru'.
    Dropout added for regularization — small corpus overfits hard.
    """
    layer_map = {"rnn": SimpleRNN, "lstm": LSTM, "gru": GRU}
    assert arch in layer_map, f"Unknown arch: {arch}"

    model = Sequential(
        [
            Embedding(total_words, 64, input_length=max_len - 1),
            layer_map[arch](units, return_sequences=False),
            Dropout(0.2),
            Dense(total_words, activation="softmax"),
        ],
        name=f"{arch.upper()}_TextGen",
    )
    model.compile(
        loss="sparse_categorical_crossentropy",
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.005),
        metrics=["accuracy"],
    )
    return model

for arch in ["rnn", "lstm", "gru"]:
    m = build_model(arch, total_words, max_len)
    dummy = np.zeros((1, max_len - 1), dtype=np.int32)
    out = m(dummy, training=False)
    assert out.shape == (1, total_words), f"Output shape mismatch for {arch}"
print("[CP2] All 3 models built & output shapes verified ✓")


EPOCHS = 200
es = EarlyStopping(monitor="loss", patience=15, restore_best_weights=True, verbose=0)
histories = {}

for arch in ["rnn", "lstm", "gru"]:
    model = build_model(arch, total_words, max_len)
    hist = model.fit(X, y, epochs=EPOCHS, callbacks=[es], verbose=0)
    histories[arch] = {"model": model, "loss": hist.history["loss"], "acc": hist.history["accuracy"]}
    final_loss = hist.history["loss"][-1]
    final_acc = hist.history["accuracy"][-1]
    epochs_ran = len(hist.history["loss"])
    print(f"[CP3] {arch.upper():<4} | Epochs: {epochs_ran:>3} | Loss: {final_loss:.4f} | Acc: {final_acc:.4f}")


def generate_text(
    model: Sequential,
    tokenizer: Tokenizer,
    seed_text: str,
    max_len: int,
    next_words: int = 7,
    temperature: float = 0.8,
) -> str:
    """
    Temperature sampling (NOT just argmax).
    temperature < 1 → conservative | > 1 → creative
    """
    idx_to_word = {v: k for k, v in tokenizer.word_index.items()}
    result = seed_text

    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([result])[0]
        token_list = pad_sequences([token_list], maxlen=max_len - 1, padding="pre")
        probs = model.predict(token_list, verbose=0)[0]

        probs = np.log(probs + 1e-8) / temperature
        probs = np.exp(probs) / np.sum(np.exp(probs))
        predicted_idx = np.random.choice(len(probs), p=probs)

        result += " " + idx_to_word.get(predicted_idx, "")

    return result.strip()


print("\n[CP4] Generated Text Samples:")
seeds = ["deep learning", "lstm helps", "neural networks"]
for seed in seeds:
    print(f"\n  Seed: '{seed}'")
    for arch in ["rnn", "lstm", "gru"]:
        out = generate_text(
            histories[arch]["model"], tokenizer, seed, max_len, next_words=7, temperature=0.7
        )
        print(f"    {arch.upper():<4}: {out}")


fig, axes = plt.subplots(1, 2, figsize=(14, 5))
colors = {"rnn": "#e74c3c", "lstm": "#2ecc71", "gru": "#3498db"}

for arch, color in colors.items():
    axes[0].plot(histories[arch]["loss"], label=arch.upper(), color=color, lw=2)
    axes[1].plot(histories[arch]["acc"], label=arch.upper(), color=color, lw=2)

axes[0].set_title("Training Loss Comparison", fontsize=13, fontweight="bold")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Loss (Sparse Categorical XEntropy)")
axes[0].legend()
axes[0].grid(alpha=0.3)

axes[1].set_title("Training Accuracy Comparison", fontsize=13, fontweight="bold")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Accuracy")
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig("loss_accuracy_comparison.png", dpi=150, bbox_inches="tight")
print("\n[CP5] Plot saved ✓")

from google.colab import files
files.download("loss_accuracy_comparison.png")


def compute_perplexity(model, X, y):
    """
    Perplexity = exp(avg NLL). Lower = better language model.
    argmax accuracy is a weak proxy — perplexity is the real metric.
    """
    probs = model.predict(X, verbose=0)
    nll = -np.mean(np.log(probs[np.arange(len(y)), y] + 1e-8))
    return np.exp(nll)


print("\n[WILDCARD] Perplexity Scores (lower = better):")
for arch in ["rnn", "lstm", "gru"]:
    ppl = compute_perplexity(histories[arch]["model"], X, y)
    print(f"  {arch.upper():<4}: {ppl:.4f}")





# FINAL SUMMARY TABLE


print("\n" + "="*60)
print(f"{'MODEL':<6} | {'FINAL LOSS':>10} | {'FINAL ACC':>9} | {'PERPLEXITY':>10}")
print("-"*60)
for arch in ["rnn", "lstm", "gru"]:
    loss = histories[arch]["loss"][-1]
    acc = histories[arch]["acc"][-1]
    ppl = compute_perplexity(histories[arch]["model"], X, y)
    print(f"{arch.upper():<6} | {loss:>10.4f} | {acc:>9.4f} | {ppl:>10.4f}")
print("="*60)